Bigtable to vector embeddings
GoogleCloudPlatform/DataflowTemplates pull request #1256
Opened 2024-01-08 22:01 UTC by ron-gal

2024-01-17 03:55 UTC, bvolpato commented on v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
> + * "https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v1/README_Cloud_Bigtable_to_GCS_JSON.md">README</a>
nit `Cloud_Bigtable_to_Vector_Embeddings`

2024-01-17 03:56 UTC, bvolpato commented on v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
> +        ValueProvider<String> doubleNumericRestrictsProvider) {
nit / style: a builder pattern here could prevent from messing up parameter orders

2024-01-17 03:57 UTC, bvolpato approved these changes
LGTM! Thanks. Just added 2 nits but no blockers

2024-01-17 03:58 UTC, bvolpato requested changes
In fact, can you please rebase / squash this into one or two commits? When looking to merge, we'd bring 38 commits to main history

2024-01-17 15:08 UTC, ron-gal commented on v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
> + * "https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v1/README_Cloud_Bigtable_to_GCS_JSON.md">README</a>
Done

2024-01-18 00:39 UTC, bvolpato submitted a review, later dismissed
LGTM, thanks!

2024-01-19 19:01 UTC, merged