Python UDF Support To Templates
GoogleCloudPlatform/DataflowTemplates pull request #1331
Opened 2024-02-13 21:46 UTC by fozzie15

Add python UDF support to templates with existing JS support.

2024-03-20 18:03 UTC, Polber requested changes

2024-03-20 18:03 UTC, Polber commented on v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
This is not needed

2024-03-20 18:03 UTC, Polber commented on v2/googlecloud-to-googlecloud/src/test/resources/TextIOToBigQueryTest/pyudf.py
> +# Copyright (C) 2018 Google LLC
nit: 2024

2024-03-20 18:03 UTC, Polber commented on v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
> +  private void pubsubToBigQueryWithPythonUdf(
nit: have 1 IT with `paramsAdder`

2024-03-20 18:08 UTC, fozzie15 commented on plugins/core-plugin/src/main/resources/Dockerfile-xlang-template
> +COPY --from=busybox:1.35.0-uclibc /bin/ls /bin/ls
Removed.

2024-03-20 18:11 UTC, fozzie15 commented on v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonExternalTextTransformer.java
> +                          "import apache_beam as beam\n"
Agreed

2024-03-20 18:12 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
> +        LOG.info(String.valueOf(failsafeObj));
Done.

2024-03-20 18:13 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
> +    }
Will do as part of future cleanup.

2024-03-20 18:13 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/test/resources/TextIOToBigQueryTest/pyudf.py
> +# Copyright (C) 2018 Google LLC
Done.

2024-03-20 18:13 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
> +  private void pubsubToBigQueryWithPythonUdf(
Will do as part of future cleanup.

2024-03-20 18:15 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
> +apache-beam[gcp,aws, azure, dataframe]==2.53.0
Done.

2024-03-20 18:15 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
> +      LOG.error("Do we even see this log?\n");
Done.

2024-03-20 18:16 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
> +                        PythonExternalTextTransformer.FailsafeRowPythonExternalUdf.ROW_SCHEMA))
Will remove as part of future cleanup.

2024-03-20 18:16 UTC, fozzie15 commented on v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
Leaving as future supported templates will use this

2024-03-20 18:16 UTC, fozzie15 commented on v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
> +              RowCoder.of(PythonExternalTextTransformer.FailsafeRowPythonExternalUdf.ROW_SCHEMA))
Will change as part of future cleanup.

2024-03-20 18:17 UTC, fozzie15 commented on plugins/core-plugin/src/main/resources/Dockerfile-xlang-template
> +ENV PIP_NO_DEPS=True
Will change as part of future cleanup.

2024-03-20 18:17 UTC, fozzie15 commented on plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
> +          generator.saveMetadata(definition, imageSpec.getMetadata(), outputClassesDirectory);
Fixed.

2024-03-20 18:17 UTC, fozzie15 commented on v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonExternalTextTransformer.java
> +                          "import apache_beam as beam\n"
Will be changed as part of future cleanup.

2024-03-20 18:17 UTC, fozzie15 commented on v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonExternalTextTransformer.java
> +    public static String string = "string";
Removed.

2024-03-20 20:56 UTC, Polber commented on plugins/core-plugin/src/main/resources/Dockerfile-xlang-template
> +COPY --from=busybox:1.35.0-uclibc /bin/ls /bin/ls
Still showing up

2024-03-20 20:58 UTC, fozzie15 commented on plugins/core-plugin/src/main/resources/Dockerfile-xlang-template
> +COPY --from=busybox:1.35.0-uclibc /bin/ls /bin/ls
Should be removed now. Hopefully gone.

2024-03-20 21:14 UTC, Polber submitted a review, later dismissed

2024-03-21 18:34 UTC, Polber approved these changes

2024-03-21 21:33 UTC, merged