[Draft][WIP]  Kafka to GCS template v2
GoogleCloudPlatform/DataflowTemplates pull request #1448
Opened 2024-04-16 22:05 UTC by AnandInguva

2024-04-22 21:22 UTC, AnandInguva commented on v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBQ.java
> +
Delete this file.

2024-04-22 21:25 UTC, AnandInguva commented on v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
> -    FailsafeElement<String, String> failsafeElement;
Add this file. accidental delete

2024-04-29 17:05 UTC, an2x requested changes

2024-04-29 20:43 UTC, AnandInguva commented on v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
> +    AVRO_SINGLE_OBJECT_ENCODING
Both are different but similar concepts. Kafka Avro uses schema IDs to get the schema from registry but single object encoding is as follows

A two-byte marker, C3 01, to show that the message is Avro and uses this single-record format (version 1).
The 8-byte little-endian CRC-64-AVRO [fingerprint](https://avro.apache.org/docs/current/specification/_print/#schema-fingerprints) of the object’s schema.
The Avro object encoded using [Avro’s binary encoding](https://avro.apache.org/docs/current/specification/_print/#binary-encoding).

I will add a doc explaining the differences.

2024-04-29 20:43 UTC, AnandInguva commented on v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
> +                  return AvroDestination.of(name1, schema.toString());
Added a TODO to modify the impl to use schema id or something compact than json schema

2024-04-29 20:44 UTC, AnandInguva commented on v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
> +      String fileName =
Changed it.

2024-04-30 21:33 UTC, an2x approved these changes

2024-04-30 21:49 UTC, an2x requested changes
Checkstyle check is failing, please fix.

2024-05-02 15:46 UTC, merged