added template kafka-to-kafka
GoogleCloudPlatform/DataflowTemplates pull request #1483
Opened 2024-04-29 08:29 UTC by Surabhiad

2024-04-29 16:56 UTC, an2x requested changes

2024-04-29 16:56 UTC, an2x commented on v2/kafka-to-kafka/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToKafkaIT.java
> +        kafkaResourceManager.buildProducer(new StringSerializer(), new StringSerializer());
I'd also add a test for binary messages, not only strings.

2024-04-29 16:56 UTC, an2x commented on v2/kafka-to-kafka/src/main/java/com/google/cloud/teleport/v2/templates/ConsumerProperties.java
> +  public static List<String> accessSecretVersion(String projectId, KafkaToKafkaOptions options) {
This code seems to be duplicated between ConsumerProperties and ProducerProperties, consider extracting it into a separate (parent?) class or combining Consumer/Producer properties somehow.

2024-04-29 16:56 UTC, an2x commented on v2/kafka-to-kafka/src/main/java/com/google/cloud/teleport/v2/options/KafkaToKafkaOptions.java
> +  String getVersionIdSourceUsername();
As discussed offline, for Username and other params, we should only have a single "secretId" parameter.

2024-04-30 19:45 UTC, an2x requested changes

2024-04-30 19:45 UTC, an2x commented on v2/kafka-to-kafka/src/main/java/com/google/cloud/teleport/v2/templates/Credentials.java
> + final class Credentials{
As discussed offline, remove this and call SecretManagerUtils directly.

2024-04-30 19:45 UTC, an2x commented on v2/kafka-to-kafka/src/main/java/com/google/cloud/teleport/v2/templates/ProducerProperties.java
> +
Please move this to the class javadoc and expand a little.

2024-05-01 01:31 UTC, an2x approved these changes

2024-05-02 15:29 UTC, merged

2024-05-03 17:46 UTC, Abacn commented
KafkaToKafkaIT.testKafkaToKafka: KafkaToKafkaIT introduced in this PR failing on main branch:

```
java.lang.IllegalArgumentException: Missing required value for [--migrationType, ""].
```