[BULK] Support custom transformations
GoogleCloudPlatform/DataflowTemplates pull request #1683
Opened 2024-06-24 09:04 UTC by Deep1998

2024-06-24 16:05 UTC, bharadwaj-aditya requested changes

2024-06-24 16:05 UTC, bharadwaj-aditya commented on v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
> +    org.joda.time.Instant endTimestamp = org.joda.time.Instant.now();
The metrics should be in a try - finally block to ensure they are always captured even there is an exception

2024-06-24 16:05 UTC, bharadwaj-aditya commented on v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
> +        throw new IllegalArgumentException("Unsupported schema type");
can you add back the details of the error here.

2024-06-24 16:05 UTC, bharadwaj-aditya commented on v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
> +  private Object handleComplexAvroTypes(
nit: Please use a more descriptive method name

2024-06-25 08:56 UTC, Deep1998 commented on cicd/internal/flags/common-flags.go
> +	moduleMap      = map[string]string{ALL: "", SPANNER: "v2/sourcedb-to-spanner/,v2/spanner-custom-shard,plugins/templates-maven-plugin"}
This was done for quickly running ITs and debugging. Will remove

2024-06-25 13:43 UTC, bharadwaj-aditya approved these changes
LGTM

2024-06-26 03:36 UTC, bharadwaj-aditya approved these changes
LGTM

2024-06-26 04:34 UTC, merged