Terraform: Add support for using pre-existing private connectivity configuration
GoogleCloudPlatform/DataflowTemplates pull request #1692
Opened 2024-06-27 10:12 UTC by manitgupta

Adds ability to specify a private connectivity configuration for the end-to-end infrastructure setup Terraform template. Private connectivity requires sensitive permissions hence the users might want to set it up manually instead of relying on automation.

**Note**: I had spent considerable time setting up MySQL 8.4 VPC setup by self-discovering how to configure a MySQL self-hosted database to work with Datastream. While I made numerous changes as per the official docs of MySQL, I am still running into errors. Current Datastream instructions are for MySQL 5.7 - https://cloud.google.com/datastream/docs/configure-self-managed-mysql. I will ask Datastream to provide documentation on how to configure MySQL 8, in the meantime switching back to MySQL 5.7.

2024-06-27 12:30 UTC, bharadwaj-aditya commented on v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf
> +  # If nothing is specified on private connectivity, IP whitelisting is
allowlisting.

2024-06-27 12:31 UTC, bharadwaj-aditya requested changes
wording change. Rest look fine.

2024-06-28 10:03 UTC, manitgupta commented on v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf
> +  # If nothing is specified on private connectivity, IP whitelisting is
Done

2024-07-01 04:08 UTC, bharadwaj-aditya approved these changes
LGTM

2024-07-01 04:29 UTC, merged