Tests: Adding Reverse Replication Tests
GoogleCloudPlatform/DataflowTemplates pull request #1951
Opened 2024-10-21 09:59 UTC by asthamohta

2024-10-21 11:25 UTC, aksharauke submitted a review, later dismissed
Just one small comment

2024-10-21 11:25 UTC, aksharauke commented on v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbNewTablesIT.java
> +  private void assertRowInMySQL() throws InterruptedException {
Skipped tables get written to 'skip' sub-directory in DLQ directory. Can we add a check for that there exists a file there?

2024-10-22 08:37 UTC, shreyakhajanchi commented on v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbNewTablesIT.java
> +  @Test
Please add a description on what CUJ is being tested

2024-10-22 08:41 UTC, shreyakhajanchi requested changes
I would recommend merging these tests into the SpannerToSourceDbIT.class that we already have, we should minimize on creating resources like dataflow job, pub/sub notification, etc since it leads to quota limits and merge tests wherever possible as is currently there in live , following the rule that if job parameter changes then only add a separate IT class for a test.

2024-11-13 10:09 UTC, aksharauke commented on v2/spanner-to-sourcedb/pom.xml
> +        <groupId>io.swagger.core.v3</groupId>
Why do we need swagger dependency?

2024-11-14 05:18 UTC, aksharauke approved these changes

2024-11-18 05:50 UTC, shreyakhajanchi commented on v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/spanner-schema.sql
> +
where is this table being used? I don't think its added in session file either

2024-11-18 09:15 UTC, shreyakhajanchi approved these changes

2024-11-18 13:27 UTC, merged