[DO NOT MERGE] Test Java 17
GoogleCloudPlatform/DataflowTemplates pull request #2050
Opened 2024-12-05 00:23 UTC by liferoad

2024-12-05 15:18 UTC, Abacn commented
there is a single test failure from the report: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2050/checks?check_run_id=33950822829

```
expected to contain hash: 81f7b7afd932b4754caaa9ba6ced7a8bcb2cbfec6857cf823e4d112125c6e939
but was                 : [org.apache.beam.it.gcp.artifacts.GcsArtifact@40673c72]
	at com.google.cloud.teleport.templates.BulkCompressorIT.baseCompress(BulkCompressorIT.java:85)
	at com.google.cloud.teleport.templates.BulkCompressorIT.testCompressGzip(BulkCompressorIT.java:55)
```

This is expected. The original assert was too strict, see

https://stackoverflow.com/questions/77305259/change-in-gzipoutputstream-behavior-in-java-17

2024-12-05 15:51 UTC, Abacn commented
Kafka PR running on https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/12183265029

Spanner PR running on https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/12183272085

2024-12-19 04:19 UTC, Polber requested changes

2024-12-19 04:19 UTC, Polber commented on .github/actions/setup-env/action.yml
> +    default: '17'
Should probably update https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/.github/actions/setup-java-env/action.yml#L33
as well

2024-12-21 16:59 UTC, liferoad commented
TODO: fix https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2050#issuecomment-2520605089

2025-01-14 14:44 UTC, liferoad commented on it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/matchers/ArtifactsSubject.java
> +                System.out.printf("Calculated Hash (no match found): {%s} \n", calculatedHash);
let us keep this since it outputs the real hash when it does not match.

2025-01-14 14:48 UTC, liferoad commented
> TODO: fix [#2050 (comment)](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2050#issuecomment-2520605089)

Done.

2025-01-14 16:09 UTC, Abacn approved these changes

2025-01-15 14:13 UTC, manitgupta commented
Thanks, all Spanner PR are passing - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/12183272085

2025-01-15 14:14 UTC, manitgupta approved these changes
CC: @bharadwaj-aditya

2025-01-15 14:43 UTC, merged