Fix DLPTextToBigQueryStreaming for multibyte characters
GoogleCloudPlatform/DataflowTemplates pull request #245
Opened 2021-05-01 18:34 UTC by naruhito

Hello,

While following the steps written in this document https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#dlptexttobigquerystreaming , I found that `DLPTextToBigQueryStreaming.java` has a minor issue for multibyte characters like Japanese names.

Before the fix:

![before-the-fix](https://user-images.githubusercontent.com/263047/116791590-5cc4a500-aaf6-11eb-938b-2fecb8734072.png)

After the fix:

![after-the-fix](https://user-images.githubusercontent.com/263047/116791597-60f0c280-aaf6-11eb-8f53-80fc38b099e4.png)

I hope this could be merged soon and become usable from GCP Cloud Console (Web UI), as we cannot use the DataFlow template for Japanese documents with PII.

Best Regards,

Naruhito

2021-05-01 18:36 UTC, naruhito commented
Let me mention @prathapreddy123

2021-05-01 21:24 UTC, prathapreddy123 requested changes

2021-05-01 21:24 UTC, prathapreddy123 commented on README.md
> +* [DLP Text to BigQuery (Streaming)](src/main/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreaming.java)
Can you move the link next to Datastore links to maintain alphabetical order

2021-05-01 21:24 UTC, prathapreddy123 commented on CONTRIBUTORS.md
>  *   Jason Kuster
Repo contributors list including statistics (commits, lines of code) etc is available through [Github Insights](https://github.com/GoogleCloudPlatform/DataflowTemplates/graphs/contributors).  In general CONTRIBUTORS.md file include names  of primary contributors who has contributed major changes.  Please exclude the file from pull request.

2021-05-02 03:17 UTC, naruhito commented
@prathapreddy123 Now updated, thank you for the quick response.

2021-05-02 03:44 UTC, prathapreddy123 approved these changes
Thanks for fixing

2021-05-03 18:37 UTC, merged