Added ApiKey support, removed username and password options
GoogleCloudPlatform/DataflowTemplates pull request #288
Opened 2021-09-03 20:19 UTC by Cherepushko

Added ApiKey support.
Username and password options were removed.

2021-09-03 20:24 UTC, Cherepushko commented
@prathapreddy123 @suyograo
ElasticsearchIO from Beam 2.31 is not compatible because it requires the following options that we're not using:
idFn indexFn routingFn typeFn docVersionFn isDeleteFn
So in this pull request I've used previous version and added apikey feature manually.

2021-09-03 23:14 UTC, suyograo commented
> ElasticsearchIO from Beam 2.31 is not compatible because it requires the following options that we're not using:
idFn indexFn routingFn typeFn docVersionFn isDeleteFn

I am not sure why 2.31 made these required. They are functions that is executed to extract the id, index, type, etc. We already pass these directly by setting them. Very weird. 

I am ok with adding this feature on top of 2.29 until we get to 2.33 (hopefully soon)

2021-09-06 02:33 UTC, prathapreddy123 requested changes

2021-09-06 02:33 UTC, prathapreddy123 commented on v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java
> +  @Description("Specify ApiKey")
Better description would be:
```
API key for access without requiring basic authentication. Refer  https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html#security-api-create-api-key-request
```

2021-09-06 16:59 UTC, prathapreddy123 approved these changes
LGTM. @suyograo - Can you please review from elastic end

2021-09-07 16:44 UTC, suyograo commented
LGTM from Elastic side. @prathapreddy123

2021-09-07 17:36 UTC, prathapreddy123 approved these changes

2021-09-08 20:14 UTC, merged