Kafka To Elasticsearch Template
GoogleCloudPlatform/DataflowTemplates pull request #305
Opened 2021-10-26 07:30 UTC by Cherepushko

This is the initial PR for **kafka-to-elasticsearch** Dataflow template. It contains **pom.xml** and the empty directories that will be filled in the future pull requests. As a placeholder for the empty folders is used **.gitkeep**.

2021-11-05 05:18 UTC, suyograo commented
@prathapreddy123 can we get a review please?

2021-11-05 13:55 UTC, prathapreddy123 commented
> @prathapreddy123 can we get a review please?

@suyograo - will review by early next week.

2021-11-07 18:28 UTC, prathapreddy123 requested changes
Directory Structure looks good.  Can you please update PR with actual business logic to avoid merging with empty directories

2022-02-11 17:53 UTC, Cherepushko commented
As discussed earlier, this PR will be reworked to use original ElasticsearchIO from Apache Beam 2.34.

2022-04-26 14:37 UTC, Cherepushko commented
Comment just to remove "stale" label.

2023-04-10 13:20 UTC, bvolpato commented
Hi @Cherepushko -- thanks for your contribution here. Unfortunately we ran behind on reviews, and the structure of the project changed a bit. Is there still interest in pursuing this template? We can work together on a plan to resolve conflicts + review the code.

2025-01-30 02:36 UTC, closed without merging