Added new templates for PubsubAvroToBigtable and PubsubProtoToBigtable
GoogleCloudPlatform/DataflowTemplates pull request #462
Opened 2022-09-06 08:02 UTC by Vasu7052

Hi Team, 

Added new v2 templates for streaming real-time binary data from Pub/Sub Subscription to a Bigtable table. I have added support for two Serialization formats which are Avro and Protobuf. Both of them have separate templates.

2022-09-12 04:17 UTC, bvolpato commented
@Vasu7052 Thanks for the contribution! Are you interested in getting this reviewed? The next step would be signing the Contributor License Agreement (CLA) as commented above.

2022-09-12 05:14 UTC, Vasu7052 commented
Hey @bvolpato. I've signed the CLA as you mentioned and the scan is reflecting the same. Please guide me through the next steps.

2022-09-15 10:46 UTC, Vasu7052 commented
R: @zhoufek

2022-09-15 13:21 UTC, bvolpato requested changes
@Vasu7052 Thanks for the contribution!
It is looking solid -- I've added a few suggestions based on a quick review. Let me know if you have any questions.

(I will leave for others to comment more on the Bigtable specifics.)

cc @Polber

2022-09-15 13:21 UTC, bvolpato commented on v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/mappers/BigQueryMappers.java
> +  /** * Section 1: Functions to build Mapper Class for each different required input ** */
nit: `/** Text. **/`

2022-09-15 13:21 UTC, bvolpato commented on v2/common/src/main/java/com/google/cloud/teleport/v2/options/BigtableCommonOptions.java
> +    @Description("Bigtable table id")
nitpick: capitalization `Bigtable Table Id`

2022-09-15 13:21 UTC, bvolpato commented on v2/pubsub-binary-to-bigtable/docs/PubSubAvroToBigtable/README.md
> +(v2/):
I think general suggestion is to execute at root, and `-pl v2/...`, can you make that adjustment?

2022-09-15 13:21 UTC, bvolpato commented on v2/pubsub-binary-to-bigtable/docs/PubSubAvroToBigtable/README.md
> +*   outputTopic: Pub/Sub topic to write dead-letter records. For example,
Can we make it something like "deadLetterTopic" or "errorOutputTopic"? in that case, I believe the name would be self-explanatory.

2022-09-15 13:21 UTC, bvolpato commented on v2/pubsub-binary-to-bigtable/src/test/java/com/google/cloud/teleport/v2/templates/TestUtils.java
> +public class TestUtils {
Could we try to make the name more specific?

2022-09-16 11:42 UTC, Vasu7052 commented
> @Vasu7052 Thanks for the contribution! It is looking solid -- I've added a few suggestions based on a quick review. Let me know if you have any questions.
> 
> (I will leave for others to comment more on the Bigtable specifics.)
> 
> cc @Polber

@bvolpato I've tried resolving your suggestions. do tell me if I miss anything or if any further changes is required.

2022-09-28 08:55 UTC, Vasu7052 commented
@bvolpato just a gentle reminder that is there any change required from my end or we can close this PR?

2022-10-05 03:11 UTC, bvolpato commented
> @bvolpato just a gentle reminder that is there any change required from my end or we can close this PR?

Hi @Vasu7052 - thanks again for contributing. It seems good from a quick glance, but I still need some time to look at it carefully (Tentative is still this week).

2022-12-07 16:46 UTC, bvolpato approved these changes

2022-12-13 12:09 UTC, Vasu7052 commented
@bvolpato can you please tell me the blocker in merging this PR?

2023-02-06 03:27 UTC, bvolpato commented
Sorry, this wasn't forgotten - we were in the middle of some large changes for templates. The templates now require metadata annotations so we can release them properly when contributed externally: https://github.com/GoogleCloudPlatform/DataflowTemplates#metadata-annotations

Do you want to add such annotations on the templates? I can also help if you prefer. I believe https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubAvroToBigQuery.java and https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java should still serve as examples.

2023-02-06 05:06 UTC, Vasu7052 commented
Sure @bvolpato , I'll do the needful changes.

2023-03-08 20:09 UTC, Vasu7052 commented
@bvolpato i've tried adding annotations to the required classes, can you please check and do let me know if anything required from my end.

2024-06-01 02:32 UTC, closed without merging